adri_tools_v2: adri_toolsV2 Class Reference
adri_toolsV2 Class Reference
#include <core.h>
Public Member Functions
adri_toolsV2 ()
~adri_toolsV2 ()
void log_filePath_set (String path)
void log_read (String &ret, boolean lineNbr)
void log_write (String &old, String timeStr)
void log_write (String &old, String timeStr, String msg)
String ch_toString (char *c)
String ch_toString (const char *c)
String literal_value (String name, String xml)
String literal_item (String name, String value)
String on_time ()
String on_time (long ms)
IPAddress string2ip (String ip)
String ip2string (IPAddress a)
int explode (String s, char sep, String *list)
String jsonAddStringsValue (boolean start, String label, String value)
String jsonAddIntValue (boolean start, String label, String value)
String jsonAddIntValue (boolean start, char *c_label, String value)
void SPIFFS_printFiles (String path)
String info_parm (String name, String value, int len=25, const char *tdb1="\t", const char *sep=" : ", const char *tdb2="", const char *last="\n")
void tempStr_print ()
String * tempStr_get (int &size)
String * tempStr_get ()
void tempStr_sizeSet (int size)
void ESP_core_info ()
void ESP_flash_info ()
void ESP_boot_info ()
String heap_string ()
void heap_print ()
void heap_monitorLoop ()
void heap_monitorToggle ()
void loop ()
Public Attributes
_telnet_setup _telnetSetup = NULL
_telnet_loop _telnetLoop = NULL
_telnet_put _telnetPut = NULL
_telnet_get _telnetGet = NULL
String * tempStrArray = nullptr
int tempStrArraySize = -1
Private Member Functions
void seconds2time (unsigned long s, char *time)
int _SPIFFS_printFiles (String path)
String boot_device (boot_flags flags)
String reset_cause (struct boot_flags flags)
Private Attributes
String log_filePath = "/log.txt"
int heap_last = 0
int heap_start = 0
boolean heap_monitor = false
Detailed Description
Definition at line 102 of file core.h.
Constructor & Destructor Documentation
adri_toolsV2()
adri_toolsV2::adri_toolsV2 ()
Definition at line 25 of file core.cpp.
{
     heap_start = ESP.getFreeHeap();
     heap_last = ESP.getFreeHeap();
     adri_toolsv2_ptr = this;
 }
References adri_toolsv2_ptr, heap_last, and heap_start.
~adri_toolsV2()
adri_toolsV2::~adri_toolsV2 () inline
Definition at line 133 of file core.h.
 {};
Member Function Documentation
_SPIFFS_printFiles()
int adri_toolsV2::_SPIFFS_printFiles (String path) private
Definition at line 283 of file core.cpp.
{
     Dir sub_dir = LittleFS.openDir(path);
     fsprintf("\t[%s]\n", path.c_str());
     int totalsize = 0;
     while (sub_dir.next()) {
         if (sub_dir.isDirectory()) _SPIFFS_printFiles(path + "/" + sub_dir.fileName());
         else {
             String sub_fileInfo = sub_dir.fileName() + (sub_dir.isDirectory() ? " [sub_dir]" : String(" (") + sub_dir.fileSize() + " b)");
             fsprintf("\t\t%s\n", sub_fileInfo.c_str());
             totalsize += sub_dir.fileSize();
         }
     }
     if (totalsize > 0) fsprintf("\t\t\t[totalsize: %d b]\n", totalsize);
     return totalsize;
 }
Referenced by SPIFFS_printFiles().
boot_device()
String adri_toolsV2::boot_device (boot_flags flags) private
Definition at line 384 of file core.cpp.
{
     String boot_device = String(flags.raw_bootdevice);
     if (flags.bootdevice_ram)   boot_device+=" (ram)";
     if (flags.bootdevice_flash) boot_device+=" (flash)";
     return boot_device;
 }
References boot_flags::bootdevice_flash, boot_flags::bootdevice_ram, and boot_flags::raw_bootdevice.
Referenced by ESP_boot_info().
ch_toString() [1/2]
String adri_toolsV2::ch_toString (char * c)
Definition at line 154 of file core.cpp.
{
     // char result[255];
     // fssprintf(result, "%s", c);
     String result((char*)c);
     return result;
 }
Referenced by jsonAddIntValue().
ch_toString() [2/2]
String adri_toolsV2::ch_toString (const char * c)
Definition at line 160 of file core.cpp.
{
        return String((const __FlashStringHelper*) c);
 }
ESP_boot_info()
void adri_toolsV2::ESP_boot_info ()
Definition at line 390 of file core.cpp.
{
     if (tempStrArray != nullptr) delete[] tempStrArray;
     tempStrArraySize    = 4;
     tempStrArray        = new String[tempStrArraySize];
     const rst_info  * resetInfo = system_get_rst_info();
     boot_flags      f           = bootmode_detect();
     tempStrArray[0] = "\nBOOT\n";
     tempStrArray[1] = info_parm(F("reset reason"), String(RST_REASONS[resetInfo->reason]), 30);
     tempStrArray[2] = info_parm(F("reset cause"),  reset_cause(f), 30);
     tempStrArray[3] = info_parm(F("boot device"),  boot_device(f), 30);
 }
References boot_device(), bootmode_detect(), info_parm(), reset_cause(), RST_REASONS, tempStrArray, and tempStrArraySize.
Referenced by adriTools_logger::spiff_setup().
ESP_core_info()
void adri_toolsV2::ESP_core_info ()
Definition at line 405 of file core.cpp.
{
     if (tempStrArray != nullptr) delete[] tempStrArray;
     tempStrArraySize    = 7;
     tempStrArray        = new String[tempStrArraySize];
     char chip_id[10];
     fssprintf(chip_id," (0x%06x)",ESP.getChipId());
     tempStrArray[0] = fsget(sys_sys);
     tempStrArray[1] = info_parm(fsget(sys_chip), ESP.getChipId()+String(chip_id), 25);
     tempStrArray[2] = info_parm(fsget(sys_core), String(ESP.getCoreVersion())+"/"+ESP.getSdkVersion());
     tempStrArray[3] = info_parm(fsget(sys_boot), String(ESP.getBootVersion()));
     tempStrArray[4] = info_parm(fsget(sys_heap), String(ESP.getFreeHeap())+"bytes");
     tempStrArray[5] = info_parm(fsget(sys_cpu),  String(ESP.getCpuFreqMHz())+"MHz");
     tempStrArray[6] = info_parm(fsget(sys_vcc),  String(ESP.getVcc())+"mV") ;
 }
References info_parm(), tempStrArray, and tempStrArraySize.
ESP_flash_info()
void adri_toolsV2::ESP_flash_info ()
Definition at line 423 of file core.cpp.
{
     if (tempStrArray != nullptr) delete[] tempStrArray;
     tempStrArraySize    = 13;
     tempStrArray        = new String[tempStrArraySize];
     tempStrArray[0] = "\nFLASH\n";
     char chip_id[20];
     fssprintf(chip_id," (0x%06x)", ESP.getFlashChipId());
     FSInfo f;
     LittleFS.info(f);
     String io;
     switch (ESP.getFlashChipMode()) {
         case FM_QIO :   io="QIO";   break;
         case FM_QOUT:   io="QOUT";  break;
         case FM_DIO :   io="DIO";   break;
         case FM_DOUT:   io="DOUT";  break;
         default     :   io="UNKNOWN";
     }
     tempStrArray[1] = info_parm(F("flash size map"),        String(FLASH_SIZE_MAP_NAMES[system_get_flash_size_map()]));
     tempStrArray[2] = info_parm(F("chip size"),             String(ESP.getFlashChipRealSize())                  );
     tempStrArray[3] = info_parm(F("ide size"),              String(ESP.getFlashChipSize())                      );
     tempStrArray[4] = info_parm(F("ide speed"),             String(ESP.getFlashChipSpeed())                     );
     tempStrArray[5] = info_parm(F("ide mode"),              io                                                  );
     tempStrArray[6] = info_parm(F("sketch size"),           String(ESP.getSketchSize())                         );
     tempStrArray[7] = info_parm(F("free space"),            String(ESP.getFreeSketchSpace())                    );
     tempStrArray[8] = (ESP.getFlashChipRealSize()!=ESP.getFlashChipSize()) ? info_parm(fsget(flash_conf), F("error")) : info_parm(fsget(flash_conf), F("ok"));
     tempStrArray[0] = "\nSPIIFS\n";
     tempStrArray[10] = info_parm(F("spiffs TotalBytes"),    String(f.totalBytes)                                );
     tempStrArray[11] = info_parm(F("spiffs UsedBytes"),     String(f.usedBytes)                                 );
     tempStrArray[12] = info_parm(F("spiffs FreeBytes"),     String(f.totalBytes-f.usedBytes)                    );
 }
References FLASH_SIZE_MAP_NAMES, info_parm(), tempStrArray, and tempStrArraySize.
explode()
int adri_toolsV2::explode (String s, char sep, String * list)
Definition at line 214 of file core.cpp.
{
     // Serial.printf("\nexplode s: %s\n", s.c_str() );
     String  t           = s + sep;
     int     str_index   = 0;
     int     list_index  = 0;
     int     j;
     String  sub;
     int size = t.length();
     while (str_index < size ) {
         j=t.indexOf(sep,str_index);
         if (j!=-1) {
             sub=t.substring(str_index, j);
             // Serial.printf("explode index:%d %s\n", str_index,sub.c_str() );
             list[list_index++]=sub;
             str_index=j+1;
         }
     }
     list[list_index]="";
     return list_index;
 }
Referenced by string2ip().
heap_monitorLoop()
void adri_toolsV2::heap_monitorLoop ()
Definition at line 472 of file core.cpp.
{
     int heap = system_get_free_heap_size();
     if (heap_last != heap) {
         if      (heap > heap_last) {fsprintf("[Remaining heap: %5d - lost: %5d] [sart: %5d - lost: %5d]\n", heap, heap-heap_last, heap_start, heap_start-heap);}
         else if (heap < heap_last) {fsprintf("[Remaining heap: %5d - gain: %5d] [sart: %5d - lost: %5d]\n", heap, heap_last-heap, heap_start, heap_start-heap);}
         heap_last = system_get_free_heap_size();
     }
 }
References heap_last, and heap_start.
Referenced by loop().
heap_monitorToggle()
void adri_toolsV2::heap_monitorToggle ()
Definition at line 482 of file core.cpp.
{
     heap_monitor = !heap_monitor;
     ADRI_LOGV(-1, 2, 2, heap_monitor, "", "");
 }
References ADRI_LOGV, and heap_monitor.
heap_print()
void adri_toolsV2::heap_print ()
Definition at line 468 of file core.cpp.
{
     int heap = system_get_free_heap_size();
     fsprintf("\n[freeheap: %6d] [sart: %5d - lost: %5d]\n", heap, heap_start, heap_start-heap) ;
 }
References heap_start.
heap_string()
String adri_toolsV2::heap_string ()
Definition at line 462 of file core.cpp.
{
   char buf[50];
   int heap = system_get_free_heap_size();
   fssprintf(buf, "[freeheap: %6d] [sart: %5d - lost: %5d]", heap, heap_start, heap_start-heap) ;
   return String(buf);
 }
References heap_start.
info_parm()
String adri_toolsV2::info_parm (String name, String value, int len = 25, const char * tdb1 = "\t", const char * sep = " : ", const char * tdb2 = "", const char * last = "\n")
Definition at line 124 of file core.cpp.
{
     String s=name;
     int size = s.length();
     while (size<len){
         s+=" ";
         size = s.length();
     }
     return tdb1+s+sep+tdb2+value+last;
 }
Referenced by ESP_boot_info(), ESP_core_info(), ESP_flash_info(), and adriTools_logger::serial_menu().
ip2string()
String adri_toolsV2::ip2string (IPAddress a)
Definition at line 193 of file core.cpp.
{
     char buf[18];
         fssprintf(buf,"%d.%d.%d.%d",a[0],a[1],a[2],a[3]);
         return String(buf);
     }
jsonAddIntValue() [1/2]
String adri_toolsV2::jsonAddIntValue (boolean start, char * c_label, String value)
Definition at line 272 of file core.cpp.
{
     String label = ch_toString(c_label);
     String ret;
     if (start)  ret =  "\""+label+"\":" +  value ;
     else        ret = ", \""+label+"\":" +  value ;
     return ret;
 }
References ch_toString().
jsonAddIntValue() [2/2]
String adri_toolsV2::jsonAddIntValue (boolean start, String label, String value)
Definition at line 266 of file core.cpp.
{
     String ret;
     if (start)  ret =  "\""+label+"\":" +  value ;
     else        ret = ", \""+label+"\":" +  value ;
     return ret;
 }
jsonAddStringsValue()
String adri_toolsV2::jsonAddStringsValue (boolean start, String label, String value)
Definition at line 260 of file core.cpp.
{
     String ret;
     if (start)  ret = "\""+label+"\":\"" +  value + "\"";
     else        ret = ", \""+label+"\":\"" +  value + "\"";
     return ret;
 }
literal_item()
String adri_toolsV2::literal_item (String name, String value)
Definition at line 252 of file core.cpp.
{
    String x="<"+name+">"+value+"</"+name+">";
    return x;
 }
literal_value()
String adri_toolsV2::literal_value (String name, String xml)
Definition at line 238 of file core.cpp.
{
    String open,close;
    String value = "";
    int start, end;
    open="<"+name+">";
    close="</"+name+">";
    start=xml.indexOf(open);
    if (start!=-1) {
       start+=name.length()+2;
       end=xml.indexOf(close);
       value=xml.substring(start,end);
    }
    return value;
 }
log_filePath_set()
void adri_toolsV2::log_filePath_set (String path)
Definition at line 66 of file core.cpp.
 {ADRI_LOG(-1, 2, 2, "", "");log_filePath = ret; }
References ADRI_LOG, and log_filePath.
log_read()
void adri_toolsV2::log_read (String & ret, boolean lineNbr)
Definition at line 67 of file core.cpp.
{
     ADRI_LOG(-1, 0, 2, "", "");
     if (lineNbr) fsprintf("\n[_log_read]\n");
     char buffer[255];
     ret = "";
     String print = "";
     int nbr = 0;
     File file = LittleFS.open(log_filePath, "r");
     if (file) {
         while (file.position()<file.size()) {
             String xml = file.readStringUntil('\n');
             if (xml != "") {
                 if (lineNbr)  {
                     sprintf(buffer, "[%15d] %s", nbr, xml.c_str());
                     print += String(buffer) + "\n";
                     fsprintf("%s\n", buffer);
                     delay(5);
                     nbr++;
                     ret += xml + "\n";
                 }
                 else ret += xml + "\n";
             }
         }
         file.close();
     }
     ADRI_LOG(-1, 1, 2, "", "");
 }
References ADRI_LOG, and log_filePath.
log_write() [1/2]
void adri_toolsV2::log_write (String & old, String timeStr)
Definition at line 94 of file core.cpp.
{
     ADRI_LOG(-1, 2, 2, "", "");
     int freeHeap = ESP.getFreeHeap();
     File file = LittleFS.open(log_filePath, "w");
     if (file) {
         char buffer[255];
         sprintf(buffer, "%15s | %15d", timeStr.c_str(), freeHeap);
         String result = old + "\n" + String(buffer);
         file.println(result);
         file.close();
         old = result;
     }
 }
References ADRI_LOG, and log_filePath.
log_write() [2/2]
void adri_toolsV2::log_write (String & old, String timeStr, String msg)
Definition at line 108 of file core.cpp.
{
     ADRI_LOG(-1, 2, 2, "", "");
     File file = LittleFS.open(log_filePath, "w");
     if (file) {
         char buffer[255];
         sprintf(buffer, "%15s | %s", timeStr.c_str(), msg.c_str());
         String result = old + "\n" + String(buffer);
         file.println(result);
         file.close();
         old = result;
     }
 }
References ADRI_LOG, and log_filePath.
loop()
void adri_toolsV2::loop ()
Definition at line 31 of file core.cpp.
{
     if (heap_monitor) heap_monitorLoop();
     if (adri_toolsv2_ptr->_telnetLoop != NULL) adri_toolsv2_ptr->_telnetLoop ();
 }
References _telnetLoop, adri_toolsv2_ptr, heap_monitor, and heap_monitorLoop().
on_time() [1/2]
String adri_toolsV2::on_time ()
Definition at line 176 of file core.cpp.
{
    char t[100];
    unsigned long offset = 0; //1000 * 60 * 60 * 24 * 3 ;
    unsigned long ms=millis()+offset;
    seconds2time(ms, t);
    return String(t);
 }
References seconds2time().
on_time() [2/2]
String adri_toolsV2::on_time (long ms)
Definition at line 184 of file core.cpp.
{
    char t[100];
    seconds2time(ms, t);
    return String(t);
 }
References seconds2time().
reset_cause()
String adri_toolsV2::reset_cause (struct boot_flags flags) private
Definition at line 377 of file core.cpp.
{
     String reset_cause=String(flags.raw_rst_cause);
     if (flags.rst_normal_boot)  reset_cause+=" (normal boot)";
     if (flags.rst_reset_pin)    reset_cause+=" (reset pin)";
     if (flags.rst_watchdog)     reset_cause+=" (watchdog reset)";
     return reset_cause;
 }
References boot_flags::raw_rst_cause, boot_flags::rst_normal_boot, boot_flags::rst_reset_pin, and boot_flags::rst_watchdog.
Referenced by ESP_boot_info().
seconds2time()
void adri_toolsV2::seconds2time (unsigned long s, char * time) private
Definition at line 167 of file core.cpp.
{
    // int milli      = (s                    ) % 1000;
    int seconds    = (s /   (1000)         ) % 60   ;
    int minutes    = (s /   (1000*60)      ) % 60   ;
    int hours      = (s /   (1000*3600)    ) % 24   ;
    int days    = (s /  (1000*3600*24)  )     ;
    sprintf(time,"%d-%02d:%02d:%02d", days, hours , minutes, seconds);
 }
Referenced by on_time().
SPIFFS_printFiles()
void adri_toolsV2::SPIFFS_printFiles (String path)
Definition at line 300 of file core.cpp.
{
     ADRI_LOG(-1, 0, 2,"","");
     Dir dir = LittleFS.openDir(path);
     Serial.println("");
     Serial.println( F("[Print file and folder]"));
     int totalsize = 0;
     while (dir.next()) {
         String fileInfo = dir.fileName() + (dir.isDirectory() ? " [DIR]" : String(" (") + dir.fileSize() + " b)");
         if (dir.isDirectory()) {
             int dSize = _SPIFFS_printFiles(dir.fileName());
             totalsize += dSize;
         } else  {
             Serial.println(fileInfo);
             totalsize += dir.fileSize();
         }
     }
     fsprintf("\n[totalsize: %d b]\n", totalsize);
     Serial.println();
     ADRI_LOG(-1, 1, 2,"","");
 }
References _SPIFFS_printFiles(), and ADRI_LOG.
string2ip()
IPAddress adri_toolsV2::string2ip (String ip)
Definition at line 199 of file core.cpp.
{
     String a[10];
     explode(ip, '.', a);
     IPAddress adr = {
         static_cast<uint8_t>(a[0].toInt()),
         static_cast<uint8_t>(a[1].toInt()),
         static_cast<uint8_t>(a[2].toInt()),
         static_cast<uint8_t>(a[3].toInt())
     };
     return adr;
 }
References explode().
tempStr_get() [1/2]
String * adri_toolsV2::tempStr_get ()
Definition at line 144 of file core.cpp.
{
     return tempStrArray;
 }
References tempStrArray.
tempStr_get() [2/2]
String * adri_toolsV2::tempStr_get (int & size)
Definition at line 140 of file core.cpp.
{
     size = tempStrArraySize;
     return tempStrArray;
 }
References tempStrArray, and tempStrArraySize.
tempStr_print()
void adri_toolsV2::tempStr_print ()
Definition at line 133 of file core.cpp.
{
     if (tempStrArraySize < 0) return;
     for (int i = 0; i < tempStrArraySize; ++i) {
         fsprintf("%s", tempStrArray[i].c_str());
         yield();
     }
 }
References tempStrArray, and tempStrArraySize.
Referenced by adriTools_logger::serial_menu().
tempStr_sizeSet()
void adri_toolsV2::tempStr_sizeSet (int size)
Definition at line 147 of file core.cpp.
{
     tempStrArraySize = size;
 }
References tempStrArraySize.
Referenced by adriTools_logger::serial_menu().
Member Data Documentation
_telnetGet
_telnet_get adri_toolsV2::_telnetGet = NULL
Definition at line 127 of file core.h.
_telnetLoop
_telnet_loop adri_toolsV2::_telnetLoop = NULL
Definition at line 125 of file core.h.
Referenced by loop().
_telnetPut
_telnet_put adri_toolsV2::_telnetPut = NULL
Definition at line 126 of file core.h.
Referenced by adriTools_print().
_telnetSetup
_telnet_setup adri_toolsV2::_telnetSetup = NULL
Definition at line 124 of file core.h.
heap_last
int adri_toolsV2::heap_last = 0 private
Definition at line 111 of file core.h.
Referenced by adri_toolsV2(), and heap_monitorLoop().
heap_monitor
boolean adri_toolsV2::heap_monitor = false private
Definition at line 113 of file core.h.
Referenced by heap_monitorToggle(), and loop().
heap_start
int adri_toolsV2::heap_start = 0 private
Definition at line 112 of file core.h.
Referenced by adri_toolsV2(), heap_monitorLoop(), heap_print(), and heap_string().
log_filePath
String adri_toolsV2::log_filePath = "/log.txt" private
Definition at line 108 of file core.h.
Referenced by log_filePath_set(), log_read(), and log_write().
tempStrArray
String* adri_toolsV2::tempStrArray = nullptr
Definition at line 129 of file core.h.
Referenced by ESP_boot_info(), ESP_core_info(), ESP_flash_info(), adriTools_logger::serial_menu(), adriTools_logger::spiff_setup(), tempStr_get(), and tempStr_print().
tempStrArraySize
int adri_toolsV2::tempStrArraySize = -1
Definition at line 130 of file core.h.
Referenced by ESP_boot_info(), ESP_core_info(), ESP_flash_info(), adriTools_logger::spiff_setup(), tempStr_get(), tempStr_print(), and tempStr_sizeSet().
The documentation for this class was generated from the following files:
core.h
core.cpp