adri_tools_v2: adriToolsLogger Class Reference
adriToolsLogger Class Reference
fournit des fonctionnalités utiles pour déboguer les croquis via "printf" ou "LITTLEFS"
#include <logger.h>
Public Member Functions
void region_start (int lvl, boolean print=false)
void region_end (int lvl, boolean print=false)
void serial_menu ()
printf des comandes disponnible
void printer_serial (boolean addLine, int region, int lvl, char *buffer)
fonction final pour le "printf" et "littfs"
void printer_timestamp_toggle ()
acitve/desactive le timestamp
void printer_heap_toggle ()
activer/desactive le freeheap
void printer_display_toggle ()
active/desactive le "printf" et "littfs" pour toutes les region
void spiff_setup ()
initialize le fichier log
void spiff_toggle ()
active/desactive le "littfs" pour toutes les region
void spiff_readCurrent ()
printf du fichier log
void spiff_removeCurrent ()
supprime le fichier log de la mem spiff
void spiff_get (String &result)
stock le fichier log dans une string
void spiff_addLine (String result)
ajoute un ligne au fichier log
void spiffAddLine_otherRegion_toggle ()
active/desactive par region < 0 le "littlfs"
void seriealPrint_otherRegion_toggle ()
active/desactive par region < 0 le "printf"
adriToolsLogger ()
~adriToolsLogger ()
boolean printer_displayMod (int region, int lvl)
fonction pour determiner si un "printf" ou "littlefs" est possible
void printer_displayMod_set (int lvl)
active le "printf" et "littfs" uniquement pour le level voullu pour toutes les region
String timeStamp ()
création du tempstamp
int strContains (char str, const char *sfind)
recherche des similitude dans une chaine de caractére
void activateByRegion_print ()
printf des regions et de leur statu
void activateByRegion_add (String name)
ajoute une region, crée une instance "activateByRegion_add"
void activateByRegion_toggle (int pos)
active/desactive totalement la region voullu
void activateByRegion_toggleAddLine (int pos)
active/desactive "littlefs" pour la region voullue
void activateByRegion_toggleSerial (int pos)
active/desactive "printf" pour la region voullue
boolean activateByRegion_stau (int pos)
obtenir si la region peut "printf" et "littlefs"
boolean activateByRegion_statuAddLine (int pos)
obtenir si la region peut "littlefs"
boolean activateByRegion_statuSerialPrint (int pos)
obtenir si la region peut "printf"
Private Attributes
int _activateByRegion_cnt = 0
nbr de class "adriToolsLogger_region" ceer
adriToolsLogger_region * _activateByRegion [10]
array cotenat les class "adriToolsLogger_region"
boolean printer_display = true
active/desactive le "printf" et "littfs" pour toute les region
int printer_displayMod_pos = 0
active le "printf" et "littfs" uniquement pour le lvl selectionner pour toute les region
boolean seriealPrint_otherRegion = true
active/desactive par region < 0 le "printf"
boolean spiff_addLine_otherRegion = true
active/desactive par region < 0 le "littfs"
boolean spiff_sav = false
active/desactive le "littfs" pour toutes les region
boolean printer_timestamp = true
acitve/desactive le timestamp
boolean printer_heap = true
activer/desactive le freeheap
String spiff_folder = "/logger"
enplacement du doosier des log situé da la mem SPIFF
String spiff_fileName = ""
nom du fichier log situé da le dossier "spiff_folder"
boolean _region_start = false
int _region_start_pos = 0
Detailed Description
fournit des fonctionnalités utiles pour déboguer les croquis via "printf" ou "LITTLEFS"
See also
https://github.com/AdriLighting/adri_tools_v2
Author
adrilighting
Date
05/02/2021 06:25:54
Definition at line 72 of file logger.h.
Constructor & Destructor Documentation
adriToolsLogger()
adriToolsLogger::adriToolsLogger ()
            @brief      constructor
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Definition at line 216 of file logger.cpp.
{
     adriToolsLogger_ptr = this;
     spiff_setup();
 }
References adriToolsLogger_ptr, and spiff_setup().
~adriToolsLogger()
adriToolsLogger::~adriToolsLogger () inline
Definition at line 146 of file logger.h.
 {};
Member Function Documentation
activateByRegion_add()
void adriToolsLogger::activateByRegion_add (String name)
ajoute une region, crée une instance "activateByRegion_add"
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Parameters
[in] pos The position
Definition at line 252 of file logger.cpp.
{
     ADRI_LOG(-1, 2, 2, "pos:%d - name:%s", _activateByRegion_cnt, name.c_str());
     _activateByRegion[_activateByRegion_cnt] = new adriToolsLogger_region(name);
     _activateByRegion_cnt++;
 }
References _activateByRegion, _activateByRegion_cnt, and ADRI_LOG.
activateByRegion_print()
void adriToolsLogger::activateByRegion_print ()
printf des regions et de leur statu
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Definition at line 231 of file logger.cpp.
{
     for (int i = 0; i < _activateByRegion_cnt; ++i)
     {
         ADRI_LOG(-1, 2, 0, "[%-5d][%-25S][state: %d][_addLine: %d][_serial: %d]",
             i,
             _activateByRegion[i]->_name.c_str(),
             _activateByRegion[i]->_state,
             _activateByRegion[i]->_addLine,
             _activateByRegion[i]->_serial
             );
     }
 }
References _activateByRegion, _activateByRegion_cnt, adriToolsLogger_region::_addLine, adriToolsLogger_region::_serial, adriToolsLogger_region::_state, and ADRI_LOG.
Referenced by adriToolLogger_serialMenu_cmd().
activateByRegion_statuAddLine()
boolean adriToolsLogger::activateByRegion_statuAddLine (int pos)
obtenir si la region peut "littlefs"
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Parameters
[in] pos poistion opur le region "_activateByRegion[pos]"
Returns
return boolean
Definition at line 313 of file logger.cpp.
{
     return _activateByRegion[pos]->statuAddLine();
 }
References _activateByRegion, and adriToolsLogger_region::statuAddLine().
Referenced by printer_serial().
activateByRegion_statuSerialPrint()
boolean adriToolsLogger::activateByRegion_statuSerialPrint (int pos)
obtenir si la region peut "printf"
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Parameters
[in] pos poistion opur le region "_activateByRegion[pos]"
Returns
return boolean
Definition at line 327 of file logger.cpp.
{
     return _activateByRegion[pos]->statuSerialPrint();
 }
References _activateByRegion, and adriToolsLogger_region::statuSerialPrint().
Referenced by printer_serial().
activateByRegion_stau()
boolean adriToolsLogger::activateByRegion_stau (int pos)
obtenir si la region peut "printf" et "littlefs"
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Parameters
[in] pos poistion opur le region "_activateByRegion[pos]"
Returns
return boolean
Definition at line 299 of file logger.cpp.
{
     return _activateByRegion[pos]->statu();
 }
References _activateByRegion, and adriToolsLogger_region::statu().
Referenced by printer_displayMod().
activateByRegion_toggle()
void adriToolsLogger::activateByRegion_toggle (int pos)
active/desactive totalement la region voullu
Definition at line 260 of file logger.cpp.
{
     _activateByRegion[pos]->toggle();
 }
References _activateByRegion, and adriToolsLogger_region::toggle().
Referenced by adriToolLogger_serialMenu_region().
activateByRegion_toggleAddLine()
void adriToolsLogger::activateByRegion_toggleAddLine (int pos)
active/desactive "littlefs" pour la region voullue
Parameters
[in] pos poistion opur le region "_activateByRegion[pos]"
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Definition at line 273 of file logger.cpp.
{
     _activateByRegion[pos]->toggleAddLine();
 }
References _activateByRegion, and adriToolsLogger_region::toggleAddLine().
Referenced by adriToolLogger_serialMenu_regionAddLine().
activateByRegion_toggleSerial()
void adriToolsLogger::activateByRegion_toggleSerial (int pos)
active/desactive "printf" pour la region voullue
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Parameters
[in] pos poistion opur le region "_activateByRegion[pos]"
Definition at line 285 of file logger.cpp.
{
     _activateByRegion[pos]->toggleSerialPrint();
 }
References _activateByRegion, and adriToolsLogger_region::toggleSerialPrint().
Referenced by adriToolLogger_serialMenu_regionSerialPrint().
printer_display_toggle()
void adriToolsLogger::printer_display_toggle ()
active/desactive le "printf" et "littfs" pour toutes les region
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Definition at line 421 of file logger.cpp.
{
     printer_display = !printer_display;
     ADRI_LOGV(-1, 2, 2, printer_display, "", "");
 }
References ADRI_LOGV, and printer_display.
Referenced by adriToolLogger_serialMenu_cmd().
printer_displayMod()
boolean adriToolsLogger::printer_displayMod (int region, int lvl)
fonction pour determiner si un "printf" ou "littlefs" est possible
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Parameters
[in] region The region
[in] lvl The level
Returns
true si un "printf" ou "littlefs" est possible
Definition at line 632 of file logger.cpp.
{
     if (!printer_display) return false;
     if (region >= 0) {
         if (!adriToolsLogger_ptrGet()->activateByRegion_stau(region)) return false;
         if (printer_displayMod_pos == 6) return false;
         if (printer_displayMod_pos == 7) {
             if (lvl < 0) return true;
             if ((lvl != 0) && (lvl != 1))   return false;
         }
         if (printer_displayMod_pos == 8) {
             if (lvl < 0) return true;
             if (lvl!=0) return false;
         }
     } else {
         if (printer_displayMod_pos == 3) return false;
         if (printer_displayMod_pos == 4) {
             if (lvl < 0) return true;
             if ((lvl != 0) && (lvl != 1)) return false;
         }
         if (printer_displayMod_pos == 5) {
             if (lvl < 0) return true;
             if (lvl!=0) return false;
         }
     }
     if (region == -2) return false;
     if (printer_displayMod_pos == 9) {
         if (lvl < 0) return true;
         if ((lvl != 0) && (lvl != 1)) return false;
     }
     if (printer_displayMod_pos == 10) {
         if (lvl < 0) return true;
         if (lvl!=0) return false;
     }
     return true;
 }
References activateByRegion_stau(), adriToolsLogger_ptrGet(), printer_display, and printer_displayMod_pos.
printer_displayMod_set()
void adriToolsLogger::printer_displayMod_set (int lvl)
active le "printf" et "littfs" uniquement pour le level voullu pour toutes les region
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Parameters
[in] lvl level voullu
Definition at line 382 of file logger.cpp.
{
     printer_displayMod_pos = lvl;
     ADRI_LOGV(-1, 2, 2, printer_displayMod_pos, "", "");
 }
References ADRI_LOGV, and printer_displayMod_pos.
Referenced by adriToolLogger_serialMenu_cmd().
printer_heap_toggle()
void adriToolsLogger::printer_heap_toggle ()
activer/desactive le freeheap
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Definition at line 409 of file logger.cpp.
{
     printer_heap = !printer_heap;
     ADRI_LOGV(-1, 2, 2, printer_heap, "", "");
 }
References ADRI_LOGV, and printer_heap.
Referenced by adriToolLogger_serialMenu_cmd().
printer_serial()
void adriToolsLogger::printer_serial (boolean addLine, int region, int lvl, char * buffer)
fonction final pour le "printf" et "littfs"
ajouter timestamp et freeheap
check si la region est activer
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Parameters
[in] addLine check if can print with "littfls"
[in] region The region
buffer The buffer
Definition at line 820 of file logger.cpp.
{
     String          result  = String(buffer);
     unsigned int    len     = result.length();
     char            bufferPrint[len + 255];
     int             heap    = ESP.getFreeHeap();
     String          cTtime;
     // adri_toolsv2Ptr_get()->ntpTime_getTime(cTtime);
     cTtime = adri_toolsv2Ptr_get()->om_time();
     const char            *color  = LOG_LEVEL_COLORS[0];
     if ((printer_timestamp) && (printer_heap)) {
         fssprintf(bufferPrint, "[%-8s][%-8d]%s", cTtime.c_str(), heap, buffer);
     }
     else {
         if (printer_timestamp)  fssprintf(bufferPrint, "[%-8s]%s", cTtime.c_str(), buffer);
         if (printer_heap)       fssprintf(bufferPrint, "[%-8d]%s", heap, buffer);
     }
     if (spiff_sav && addLine) {
         if (region >= 0) {
              if (adriToolsLogger_ptrGet()->activateByRegion_statuAddLine(region)) {spiff_addLine(String(bufferPrint));}
         } else {
             if (spiff_addLine_otherRegion) spiff_addLine(String(bufferPrint));
         }
     }
     boolean sPrint = false;
     if (region >= 0) {
          if (adriToolsLogger_ptrGet()->activateByRegion_statuSerialPrint(region)) {sPrint = true;}
     } else {
         if (seriealPrint_otherRegion) sPrint = true;
     }
     if (sPrint) {
         // fsprintf("%s\n", bufferPrint);
         Serial.println(bufferPrint);
         if (adri_toolsv2Ptr_get() != nullptr) {
             if (adri_toolsv2Ptr_get()->_telnetPut != NULL) {
                 int pos = 0;
                 switch (lvl) {
                     case -1:
                         pos = 7;
                     break;
                     case -2:
                         pos = 6;
                     break;
                     case 0:
                         pos = 2;
                     break;
                     case 1:
                         pos = 2;
                     break;
                     case 2:
                         pos = 3;
                     break;
                     default:
                         pos = 7;
                     break;
                 }
                 color = LOG_LEVEL_COLORS[pos];
                 String fBuffer = String(bufferPrint);
                 fssprintf(bufferPrint, "%s%s\n", color, fBuffer.c_str());
                 adri_toolsv2Ptr_get()->_telnetPut(String(bufferPrint));
             }
         }
     }
 }
References adri_toolsV2::_telnetPut, activateByRegion_statuAddLine(), activateByRegion_statuSerialPrint(), adri_toolsv2Ptr_get(), adriToolsLogger_ptrGet(), LOG_LEVEL_COLORS, adri_toolsV2::om_time(), printer_heap, printer_timestamp, seriealPrint_otherRegion, spiff_addLine(), spiff_addLine_otherRegion, and spiff_sav.
Referenced by esp_log_print_lines().
printer_timestamp_toggle()
void adriToolsLogger::printer_timestamp_toggle ()
acitve/desactive le timestamp
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Definition at line 397 of file logger.cpp.
{
     printer_timestamp = !printer_timestamp;
     ADRI_LOGV(-1, 2, 2, printer_timestamp, "", "");
 }
References ADRI_LOGV, and printer_timestamp.
Referenced by adriToolLogger_serialMenu_cmd().
region_end()
void adriToolsLogger::region_end (int lvl, boolean print = false)
Definition at line 801 of file logger.cpp.
{
      _region_start = false;
      _region_start_pos = 0;
     // if (print) ADRI_LOG(lvl, -2, 0, "---->>>", "");
 }
References _region_start, and _region_start_pos.
region_start()
void adriToolsLogger::region_start (int lvl, boolean print = false)
Definition at line 797 of file logger.cpp.
{
     _region_start = true;
     // if (print) ADRI_LOG(lvl, -2, 0, "----<<<", "");
 }
References _region_start.
serial_menu()
void adriToolsLogger::serial_menu ()
printf des comandes disponnible
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Definition at line 586 of file logger.cpp.
{
     adri_toolsV2 * _ptr = adri_toolsv2Ptr_get();
     if (_ptr->tempStrArray != nullptr) delete[] _ptr->tempStrArray;
     int size = 23;
     _ptr->tempStr_sizeSet(size);
     _ptr->tempStrArray          = new String[size];
     _ptr->tempStrArray[0]       = "\nPrinter lvl\n";
     _ptr->tempStrArray[1]       = _ptr->info_parm(F("0"),       F("all"), 10);
     _ptr->tempStrArray[2]       = _ptr->info_parm(F("1"),       F("all + only header bt "), 10);
     _ptr->tempStrArray[3]       = _ptr->info_parm(F("2"),       F("all + only header t "), 10);
     _ptr->tempStrArray[4]       = _ptr->info_parm(F("3"),       F("only region"), 10);
     _ptr->tempStrArray[5]       = _ptr->info_parm(F("4"),       F("only region + only header bt"), 10);
     _ptr->tempStrArray[6]       = _ptr->info_parm(F("5"),       F("only region + only header t"), 10);
     _ptr->tempStrArray[7]       = _ptr->info_parm(F("6"),       F("no region"), 10);
     _ptr->tempStrArray[8]       = _ptr->info_parm(F("7"),       F("no region + only header bt"), 10);
     _ptr->tempStrArray[9]       = _ptr->info_parm(F("8"),       F("no region + only header t"), 10);
     _ptr->tempStrArray[10]      = _ptr->info_parm(F("9"),       F("only bt"), 10);
     _ptr->tempStrArray[11]      = _ptr->info_parm(F("10"),      F("only t"), 10);
     _ptr->tempStrArray[12]      = "\nMenu\n";
     _ptr->tempStrArray[13]      = _ptr->info_parm(F("a"),       F("menu"), 10);
     _ptr->tempStrArray[14]      = _ptr->info_parm(F("z"),       F("printer_display_toggle"), 10);
     _ptr->tempStrArray[15]      = _ptr->info_parm(F("e"),       F("printer_heap_toggle"), 10);
     _ptr->tempStrArray[16]      = _ptr->info_parm(F("r"),       F("printer_timestamp_toggle"), 10);
     _ptr->tempStrArray[17]      = _ptr->info_parm(F("t"),       F("spiff activate"), 10);
     _ptr->tempStrArray[18]      = _ptr->info_parm(F("y"),       F("spiff read"), 10);
     _ptr->tempStrArray[19]      = _ptr->info_parm(F("u"),       F("spiff remove"), 10);
     _ptr->tempStrArray[20]      = _ptr->info_parm(F("i"),       F("toggle spifAddline lvl -1"), 10);
     _ptr->tempStrArray[21]      = _ptr->info_parm(F("o"),       F("toggle serialPrint lvl -1"), 10);
     _ptr->tempStrArray[22]      = _ptr->info_parm(F("p"),   F("print region"), 10);
     _ptr->tempStr_print();
 }
References adri_toolsv2Ptr_get(), adri_toolsV2::info_parm(), adri_toolsV2::tempStr_print(), adri_toolsV2::tempStr_sizeSet(), and adri_toolsV2::tempStrArray.
Referenced by adriToolLogger_serialMenu_cmd().
seriealPrint_otherRegion_toggle()
void adriToolsLogger::seriealPrint_otherRegion_toggle ()
active/desactive par region < 0 le "printf"
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Definition at line 457 of file logger.cpp.
{
     seriealPrint_otherRegion = !seriealPrint_otherRegion;
     ADRI_LOGV(-1, 2, 2, seriealPrint_otherRegion, "", "");
 }
References ADRI_LOGV, and seriealPrint_otherRegion.
Referenced by adriToolLogger_serialMenu_cmd().
spiff_addLine()
void adriToolsLogger::spiff_addLine (String result)
ajoute un ligne au fichier log
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Parameters
[in] result la ligne a ajouter
Definition at line 1019 of file logger.cpp.
{
     // String old;
     // spiff_get(old);
     File file = LittleFS.open(spiff_folder+"/"+spiff_fileName, "a");
     file.println(result);
     file.close();
 }
References spiff_fileName, and spiff_folder.
Referenced by printer_serial(), and spiff_setup().
spiff_get()
void adriToolsLogger::spiff_get (String & ret)
stock le fichier log dans une string
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Parameters
[int/out] result totalitée du fichier log
Definition at line 989 of file logger.cpp.
{
         // ADRI_LOG(-1, 0, 2,"","");
     String lines = "";
     File file = LittleFS.open(spiff_folder+"/"+spiff_fileName, "r");
     if (file) {
         while (file.position()<file.size()) {
             String xml = file.readStringUntil('\n');
             if (xml != "") {
                                 lines += xml + "\n";
             }
         }
         file.close();
     }
     ret = lines;
         // ADRI_LOG(-1, 1, 2,"","");
 }
References spiff_fileName, and spiff_folder.
spiff_readCurrent()
void adriToolsLogger::spiff_readCurrent ()
printf du fichier log
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Definition at line 1035 of file logger.cpp.
{
     ADRI_LOG(-1, 0, 2, "", "");
     fsprintf("\n[spiff_readCurrent]\n");
     char buffer[512];
     String print = "";
     int nbr = 0;
     File file = LittleFS.open(spiff_folder+"/"+spiff_fileName, "r");
     if (file) {
         while (file.position()<file.size()) {
             String xml = file.readStringUntil('\n');
             if (xml != "") {
                 // Serial.println(xml);
                 sprintf(buffer, "[%5d] %s", nbr, xml.c_str());
                 print += String(buffer) + "\n";
                 fsprintf("%s\n", buffer);
                 delay(5);
                 nbr++;
             }
         }
         file.close();
     }
     ADRI_LOG(-1, 1, 2, "", "");
 }
References ADRI_LOG, spiff_fileName, and spiff_folder.
Referenced by adriToolLogger_serialMenu_cmd().
spiff_removeCurrent()
void adriToolsLogger::spiff_removeCurrent ()
supprime le fichier log de la mem spiff
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Definition at line 1067 of file logger.cpp.
{
         LittleFS.remove(spiff_folder+"/"+spiff_fileName);
 }
References spiff_fileName, and spiff_folder.
Referenced by adriToolLogger_serialMenu_cmd().
spiff_setup()
void adriToolsLogger::spiff_setup ()
initialize le fichier log
utiliser pour chaque demmarage de l'esp, inscript dans le fichier log la raisson du dernier reset de l'esp
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Definition at line 949 of file logger.cpp.
{
         ADRI_LOG(-1, 0, 2,"","");
     // Dir dir = LittleFS.openDir(spiff_folder);
     // int totalFile = 0;
     // while (dir.next()) {
     //     if (dir.isDirectory()) {
     //     } else  {
     //          totalFile++;
     //     }
     // }
     // spiff_fileName = String(totalFile+1) + ".txt";
         spiff_fileName = "log.txt";
         spiff_addLine("\n");
         adri_toolsV2 * _tools = adri_toolsv2Ptr_get();
         _tools->ESP_boot_info();
         int size = _tools->tempStrArraySize;
         for (int i = 0; i < size; ++i)
         {
                 spiff_addLine(_tools->tempStrArray[i]);
         }
         ADRI_LOG(-1, 1, 2,"","");
 }
References ADRI_LOG, adri_toolsv2Ptr_get(), adri_toolsV2::ESP_boot_info(), spiff_addLine(), spiff_fileName, adri_toolsV2::tempStrArray, and adri_toolsV2::tempStrArraySize.
Referenced by adriToolsLogger().
spiff_toggle()
void adriToolsLogger::spiff_toggle ()
active/desactive le "littfs" pour toutes les region
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Definition at line 433 of file logger.cpp.
{
     spiff_sav = !spiff_sav;
     ADRI_LOGV(-1, 2, 2, spiff_sav, "", "");
 }
References ADRI_LOGV, and spiff_sav.
Referenced by adriToolLogger_serialMenu_cmd().
spiffAddLine_otherRegion_toggle()
void adriToolsLogger::spiffAddLine_otherRegion_toggle ()
active/desactive par region < 0 le "littlfs"
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Definition at line 445 of file logger.cpp.
{
     spiff_addLine_otherRegion = !spiff_addLine_otherRegion;
     ADRI_LOGV(-1, 2, 2, spiff_addLine_otherRegion, "", "");
 }
References ADRI_LOGV, and spiff_addLine_otherRegion.
Referenced by adriToolLogger_serialMenu_cmd().
strContains()
int adriToolsLogger::strContains (char str, const char * sfind)
recherche des similitude dans une chaine de caractére
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Parameters
[in] str le caractére a chercher
[in] sfind la chaine a analyser
Returns
le nombre de similitude
Definition at line 360 of file logger.cpp.
{
     int result = 0;
     int len = strlen(sfind);
     for (int i = 0; i < len; ++i) {
         if ( sfind[i] == str ) result++;
     }
     return result;
 }
References ArduinoTrace::strlen().
Referenced by esp_log_print_lines().
timeStamp()
String adriToolsLogger::timeStamp ()
création du tempstamp
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Returns
string
Definition at line 342 of file logger.cpp.
 {
   char result[20];
   snprintf(result, 20, "%lu", millis());
   return String(result);
 }
Member Data Documentation
_activateByRegion
adriToolsLogger_region* adriToolsLogger::_activateByRegion[10] private
array cotenat les class "adriToolsLogger_region"
Definition at line 77 of file logger.h.
Referenced by activateByRegion_add(), activateByRegion_print(), activateByRegion_statuAddLine(), activateByRegion_statuSerialPrint(), activateByRegion_stau(), activateByRegion_toggle(), activateByRegion_toggleAddLine(), and activateByRegion_toggleSerial().
_activateByRegion_cnt
int adriToolsLogger::_activateByRegion_cnt = 0 private
nbr de class "adriToolsLogger_region" ceer
Definition at line 75 of file logger.h.
Referenced by activateByRegion_add(), and activateByRegion_print().
_region_start
boolean adriToolsLogger::_region_start = false private
Definition at line 105 of file logger.h.
Referenced by region_end(), and region_start().
_region_start_pos
int adriToolsLogger::_region_start_pos = 0 private
Definition at line 106 of file logger.h.
Referenced by region_end().
printer_display
boolean adriToolsLogger::printer_display = true private
active/desactive le "printf" et "littfs" pour toute les region
Definition at line 80 of file logger.h.
Referenced by printer_display_toggle(), and printer_displayMod().
printer_displayMod_pos
int adriToolsLogger::printer_displayMod_pos = 0 private
active le "printf" et "littfs" uniquement pour le lvl selectionner pour toute les region
Definition at line 83 of file logger.h.
Referenced by printer_displayMod(), and printer_displayMod_set().
printer_heap
boolean adriToolsLogger::printer_heap = true private
activer/desactive le freeheap
Definition at line 97 of file logger.h.
Referenced by printer_heap_toggle(), and printer_serial().
printer_timestamp
boolean adriToolsLogger::printer_timestamp = true private
acitve/desactive le timestamp
Definition at line 94 of file logger.h.
Referenced by printer_serial(), and printer_timestamp_toggle().
seriealPrint_otherRegion
boolean adriToolsLogger::seriealPrint_otherRegion = true private
active/desactive par region < 0 le "printf"
Definition at line 86 of file logger.h.
Referenced by printer_serial(), and seriealPrint_otherRegion_toggle().
spiff_addLine_otherRegion
boolean adriToolsLogger::spiff_addLine_otherRegion = true private
active/desactive par region < 0 le "littfs"
Definition at line 88 of file logger.h.
Referenced by printer_serial(), and spiffAddLine_otherRegion_toggle().
spiff_fileName
String adriToolsLogger::spiff_fileName = "" private
nom du fichier log situé da le dossier "spiff_folder"
Definition at line 103 of file logger.h.
Referenced by spiff_addLine(), spiff_get(), spiff_readCurrent(), spiff_removeCurrent(), and spiff_setup().
spiff_folder
String adriToolsLogger::spiff_folder = "/logger" private
enplacement du doosier des log situé da la mem SPIFF
Definition at line 100 of file logger.h.
Referenced by spiff_addLine(), spiff_get(), spiff_readCurrent(), and spiff_removeCurrent().
spiff_sav
boolean adriToolsLogger::spiff_sav = false private
active/desactive le "littfs" pour toutes les region
Definition at line 91 of file logger.h.
Referenced by printer_serial(), and spiff_toggle().
The documentation for this class was generated from the following files:
logger.h
logger.cpp