adri_tools_v2: core.h File Reference
core.h File Reference
#include <arduino.h>
#include "ArduinoTrace.h"
Classes
struct boot_flags
class adri_toolsV2
Macros
#define ARRAY_SIZE(A) (sizeof(A) / sizeof((A)[0]))
#define adri_log_v(parm_e, parm_d, parm_c, parm_b, parm_a, ...)
#define adri_log_(parm_d, parm_c, parm_b, parm_a, ...)
#define adri_log_f(parm_e, parm_d, parm_c, parm_b, parm_a, ...)
#define ADRI_LOGV(parm_e, parm_d, parm_c, parm_b, parm_a, ...) adri_log_v(parm_e, parm_d, parm_c, parm_b, parm_a, __VA_ARGS__)
#define ADRI_LOG(parm_d, parm_c, parm_b, parm_a, ...) adri_log_(parm_d, parm_c, parm_b, parm_a, __VA_ARGS__)
printf
#define ADRI_LOGP(parm_e, parm_d, parm_c, parm_b, parm_a, ...) adri_log_f(parm_e, parm_d, parm_c, parm_b, parm_a, __VA_ARGS__)
Typedefs
typedef void(* _telnet_setup) ()
typedef void(* _telnet_loop) ()
typedef void(* _telnet_put) (String output_string)
typedef boolean(* _telnet_get) (String &input_string)
Functions
void adriTools_print (String buf)
{ function_description }
void adriTools_printLn (String buf)
void esp_log_printf_ (int actf, int lvl, int mod, String line, String func, String var, const char *tag)
void esp_log_printf_ (int actf, int lvl, int mod, String line, String func, const char *tag)
void esp_log_printf_ (boolean addLine, int actf, int lvl, int mod, String line, String func, const char *tag)
adri_toolsV2 * adri_toolsv2Ptr_get ()
Variables
String ARDUINOTRACE_EXTERN_STRING
String ARDUINOTRACE_LINE
String ARDUINOTRACE_FUNC
String ARDUINOTRACE_VAR
char adriTools_PrBuffer []
const char PROGMEM adriTools_ch_cr []
Macro Definition Documentation
ADRI_LOG
#define ADRI_LOG (parm_d, parm_c, parm_b, parm_a, ...) adri_log_(parm_d, parm_c, parm_b, parm_a, __VA_ARGS__)
printf
Parameters
parm_d region
parm_c lvl
parm_b trace
parm_a param
... args
Returns
{ description_of_the_return_value }
Definition at line 82 of file core.h.
adri_log_
#define adri_log_ (parm_d, parm_c, parm_b, parm_a, ...)
Value:
                ARDUINOTRACE_TRACEL()                                                                                                                   \
                ARDUINOTRACE_TRACEF()                                                                                                                   \
                sprintf_P(adriTools_PrBuffer, (PGM_P)PSTR(parm_a), ##__VA_ARGS__) ;                             \
                esp_log_printf_(parm_d, parm_c, parm_b, ARDUINOTRACE_LINE, ARDUINOTRACE_FUNC, adriTools_PrBuffer)
Definition at line 59 of file core.h.
adri_log_f
#define adri_log_f (parm_e, parm_d, parm_c, parm_b, parm_a, ...)
Value:
                ARDUINOTRACE_TRACEL()                                                                                                                   \
                ARDUINOTRACE_TRACEF()                                                                                                                   \
                sprintf_P(adriTools_PrBuffer, (PGM_P)PSTR(parm_a), ##__VA_ARGS__) ;                             \
                esp_log_printf_(parm_e, parm_d, parm_c, parm_b, ARDUINOTRACE_LINE, ARDUINOTRACE_FUNC, adriTools_PrBuffer)
Definition at line 65 of file core.h.
adri_log_v
#define adri_log_v (parm_e, parm_d, parm_c, parm_b, parm_a, ...)
Value:
                ARDUINOTRACE_TRACEL()                                                                                                                   \
                ARDUINOTRACE_TRACEF()                                                                                                                   \
                ARDUINOTRACE_DUMPL(parm_b)                                                                                                              \
                sprintf_P(adriTools_PrBuffer, (PGM_P)PSTR(parm_a), ##__VA_ARGS__) ;                             \
                esp_log_printf_(parm_e, parm_d, parm_c, ARDUINOTRACE_LINE, ARDUINOTRACE_FUNC, ARDUINOTRACE_VAR, adriTools_PrBuffer)
Definition at line 52 of file core.h.
ADRI_LOGP
#define ADRI_LOGP (parm_e, parm_d, parm_c, parm_b, parm_a, ...) adri_log_f(parm_e, parm_d, parm_c, parm_b, parm_a, __VA_ARGS__)
Definition at line 83 of file core.h.
ADRI_LOGV
#define ADRI_LOGV (parm_e, parm_d, parm_c, parm_b, parm_a, ...) adri_log_v(parm_e, parm_d, parm_c, parm_b, parm_a, __VA_ARGS__)
Definition at line 71 of file core.h.
ARRAY_SIZE
#define ARRAY_SIZE (A) (sizeof(A) / sizeof((A)[0]))
Definition at line 18 of file core.h.
Typedef Documentation
_telnet_get
typedef boolean(* _telnet_get) (String &input_string)
Definition at line 101 of file core.h.
_telnet_loop
typedef void(* _telnet_loop) ()
Definition at line 99 of file core.h.
_telnet_put
typedef void(* _telnet_put) (String output_string)
Definition at line 100 of file core.h.
_telnet_setup
typedef void(* _telnet_setup) ()
Definition at line 98 of file core.h.
Function Documentation
adri_toolsv2Ptr_get()
adri_toolsV2* adri_toolsv2Ptr_get ()
Definition at line 21 of file core.cpp.
{
     if (adri_toolsv2_ptr==nullptr) adri_toolsv2_ptr = new adri_toolsV2();
     return adri_toolsv2_ptr;
 }
References adri_toolsv2_ptr.
Referenced by adriTools_logger::serial_menu(), and adriTools_logger::spiff_setup().
adriTools_print()
void adriTools_print (String buf)
{ function_description }
Parameters
[in] path The path
Returns
{ description_of_the_return_value }
Definition at line 51 of file core.cpp.
{
     if (adri_toolsv2_ptr!=nullptr) {
         if (adri_toolsv2_ptr->_telnetPut != NULL) {
             adri_toolsv2_ptr->_telnetPut(buf);
         }
     }
     Serial.print(buf);
 }
References adri_toolsV2::_telnetPut, and adri_toolsv2_ptr.
adriTools_printLn()
void adriTools_printLn (String buf)
Definition at line 59 of file core.cpp.
 {Serial.println(buf);}
esp_log_printf_() [1/3]
void esp_log_printf_ (boolean addLine, int actf, int lvl, int mod, String line, String func, const char * tag)
Definition at line 689 of file logger.cpp.
{
     if (!adriTools_logger_ptrGet()->printer_displayMod(region, lvl)) return;
     String pLine = "";
     switch (mod) {
         case 1:
             pLine = line;
             break;
         case 2:
             pLine = line + " " + func;
             break;
         default:
             break;
     }
     esp_log_print_lines(addLine, region, lvl, mod, pLine, func, (char*)"", tag );
 }
References adriTools_logger_ptrGet(), and esp_log_print_lines().
esp_log_printf_() [2/3]
void esp_log_printf_ (int actf, int lvl, int mod, String line, String func, const char * tag)
Definition at line 674 of file logger.cpp.
{
     if (!adriTools_logger_ptrGet()->printer_displayMod(region, lvl)) return;
     String pLine = "";
     switch (mod) {
         case 1:
             pLine = line;
             break;
         case 2:
             pLine = line + " " + func;
             break;
         default:
             break;
     }
     esp_log_print_lines(true, region, lvl, mod, pLine, func, (char*)"", tag );
 }
References adriTools_logger_ptrGet(), and esp_log_print_lines().
esp_log_printf_() [3/3]
void esp_log_printf_ (int actf, int lvl, int mod, String line, String func, String var, const char * tag)
Definition at line 659 of file logger.cpp.
{
     if (!adriTools_logger_ptrGet()->printer_displayMod(region, lvl)) return;
     String pLine = "";
     switch (mod) {
         case 1:
             pLine = line;
             break;
         case 2:
             pLine = line + " " + func;
             break;
         default:
             break;
     }
     esp_log_print_lines(true, region, lvl, mod, pLine, func, var, tag );
 }
References adriTools_logger_ptrGet(), and esp_log_print_lines().
Variable Documentation
adriTools_ch_cr
const char PROGMEM adriTools_ch_cr[]
Definition at line 16 of file core.cpp.
adriTools_PrBuffer
char adriTools_PrBuffer[]
Definition at line 40 of file core.cpp.
ARDUINOTRACE_EXTERN_STRING
String ARDUINOTRACE_EXTERN_STRING
Definition at line 10 of file core.cpp.
Referenced by ArduinoTrace::PrinterF< TFilename, TPrefix >::PrinterF().
ARDUINOTRACE_FUNC
String ARDUINOTRACE_FUNC
Definition at line 12 of file core.cpp.
Referenced by ArduinoTrace::PrinterL< TFilename, TPrefix >::PrinterL().
ARDUINOTRACE_LINE
String ARDUINOTRACE_LINE
Definition at line 11 of file core.cpp.
Referenced by ArduinoTrace::PrinterL< TFilename, TPrefix >::PrinterL().
ARDUINOTRACE_VAR
String ARDUINOTRACE_VAR
Definition at line 13 of file core.cpp.
Referenced by ArduinoTrace::PrinterD< TPrefix >::PrinterD().