adri_tools_v2: logger.cpp File Reference
logger.cpp File Reference
fournit des fonctionnalités utiles pour déboguer les croquis via "printf" ou "LITTLEFS"
#include "logger.h"
Macros
#define ADRITOOLSLOGGER_COLOR_BLACK "30"
#define ADRITOOLSLOGGER_COLOR_RED "31"
#define ADRITOOLSLOGGER_COLOR_GREEN "32"
#define ADRITOOLSLOGGER_COLOR_YELLOW "33"
#define ADRITOOLSLOGGER_COLOR_BLUE "34"
#define ADRITOOLSLOGGER_COLOR_MAGENTA "35"
#define ADRITOOLSLOGGER_COLOR_CYAN "36"
#define ADRITOOLSLOGGER_COLOR_GRAY "37"
#define ADRITOOLSLOGGER_COLOR_WHITE "38"
#define ADRITOOLSLOGGER_SECRET_BEGIN "\033[5m"
#define ADRITOOLSLOGGER_SECRET_END "\033[6m"
#define ADRITOOLSLOGGER_COLOR(COLOR) "\033[0;" COLOR "m"
#define ADRITOOLSLOGGER_BOLD(COLOR) "\033[1;" COLOR "m"
#define ADRITOOLSLOGGER_RESET_COLOR "\033[0m"
Functions
adriToolsLogger * adriToolsLogger_ptrGet ()
ptr ver la dernierre instance de la classe "adriToolsLogger"
String adriToolLogger_serialMenu_region (String cmd, String value)
fonction pour le keyboard, active/desactive totalement la region voullu
String adriToolLogger_serialMenu_regionAddLine (String cmd, String value)
fonction pour le keyboard, active/desactive "littlefs" pour la region voullue
String adriToolLogger_serialMenu_regionSerialPrint (String cmd, String value)
fonction pour le keyboard, active/desactive "printf" pour la region voullue
String adriToolLogger_serialMenu_cmd (String cmd, String value)
fonction pour le keyboard, commnds menu
void esp_log_print_lines (boolean addLine, int region, int lvl, int mod, String pLine, String func, String var, const char *tag)
void esp_log_printf_ (int region, int lvl, int mod, String line, String func, String var, const char *tag)
void esp_log_printf_ (int region, int lvl, int mod, String line, String func, const char *tag)
void esp_log_printf_ (boolean addLine, int region, int lvl, int mod, String line, String func, const char *tag)
Variables
static const char * LOG_LEVEL_COLORS []
char adriLogger_buffer1 [1024]
adriToolsLogger * adriToolsLogger_ptr = nullptr
Detailed Description
fournit des fonctionnalités utiles pour déboguer les croquis via "printf" ou "LITTLEFS"
See also
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Definition in file logger.cpp.
Macro Definition Documentation
ADRITOOLSLOGGER_BOLD
#define ADRITOOLSLOGGER_BOLD (COLOR) "\033[1;" COLOR "m"
Definition at line 90 of file logger.cpp.
ADRITOOLSLOGGER_COLOR
#define ADRITOOLSLOGGER_COLOR (COLOR) "\033[0;" COLOR "m"
Definition at line 89 of file logger.cpp.
ADRITOOLSLOGGER_COLOR_BLACK
#define ADRITOOLSLOGGER_COLOR_BLACK "30"
Definition at line 77 of file logger.cpp.
ADRITOOLSLOGGER_COLOR_BLUE
#define ADRITOOLSLOGGER_COLOR_BLUE "34"
Definition at line 81 of file logger.cpp.
ADRITOOLSLOGGER_COLOR_CYAN
#define ADRITOOLSLOGGER_COLOR_CYAN "36"
Definition at line 83 of file logger.cpp.
ADRITOOLSLOGGER_COLOR_GRAY
#define ADRITOOLSLOGGER_COLOR_GRAY "37"
Definition at line 84 of file logger.cpp.
ADRITOOLSLOGGER_COLOR_GREEN
#define ADRITOOLSLOGGER_COLOR_GREEN "32"
Definition at line 79 of file logger.cpp.
ADRITOOLSLOGGER_COLOR_MAGENTA
#define ADRITOOLSLOGGER_COLOR_MAGENTA "35"
Definition at line 82 of file logger.cpp.
ADRITOOLSLOGGER_COLOR_RED
#define ADRITOOLSLOGGER_COLOR_RED "31"
Definition at line 78 of file logger.cpp.
ADRITOOLSLOGGER_COLOR_WHITE
#define ADRITOOLSLOGGER_COLOR_WHITE "38"
Definition at line 85 of file logger.cpp.
ADRITOOLSLOGGER_COLOR_YELLOW
#define ADRITOOLSLOGGER_COLOR_YELLOW "33"
Definition at line 80 of file logger.cpp.
ADRITOOLSLOGGER_RESET_COLOR
#define ADRITOOLSLOGGER_RESET_COLOR "\033[0m"
Definition at line 91 of file logger.cpp.
ADRITOOLSLOGGER_SECRET_BEGIN
#define ADRITOOLSLOGGER_SECRET_BEGIN "\033[5m"
Definition at line 86 of file logger.cpp.
ADRITOOLSLOGGER_SECRET_END
#define ADRITOOLSLOGGER_SECRET_END "\033[6m"
Definition at line 87 of file logger.cpp.
Function Documentation
adriToolLogger_serialMenu_cmd()
String adriToolLogger_serialMenu_cmd (String cmd, String value)
fonction pour le keyboard, commnds menu
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Parameters
[in] cmd The command
[in] value The value
Returns
""
Definition at line 545 of file logger.cpp.
{
     adriToolsLogger * _looger = adriToolsLogger_ptrGet();
     ADRI_LOGP(false, -1, -1, 0, "<<<", "");
     ADRI_LOGP(false, -1, 0, 2,"","");
     ADRI_LOGP(false, -1, 2, 2, "cmd: %s - value: %S", cmd.c_str(), value.c_str());
     int pos = value.toInt();
     if (value == "a") {
         _looger->serial_menu();
     } else if (value == "z") {
         _looger->printer_display_toggle();
     } else if (value == "e") {
         _looger->printer_heap_toggle();
     } else if (value == "r") {
         _looger->printer_timestamp_toggle();
     } else if (value == "t") {
         _looger->spiff_toggle();
     } else if (value == "y") {
         _looger->spiff_readCurrent();
     } else if (value == "u") {
         _looger->spiff_removeCurrent();
     } else if (value == "i") {
         _looger->spiffAddLine_otherRegion_toggle();
     } else if (value == "o") {
         _looger->seriealPrint_otherRegion_toggle();
     } else if (value == "p") {
         _looger->activateByRegion_print();
     } else {
         _looger->printer_displayMod_set(pos);
     }
     ADRI_LOGP(false, -1, 1, 2,"","");
     ADRI_LOGP(false, -1, -1, 0, ">>>", "");
     return "";
 }
References adriToolsLogger::activateByRegion_print(), ADRI_LOGP, adriToolsLogger_ptrGet(), adriToolsLogger::printer_display_toggle(), adriToolsLogger::printer_displayMod_set(), adriToolsLogger::printer_heap_toggle(), adriToolsLogger::printer_timestamp_toggle(), adriToolsLogger::serial_menu(), adriToolsLogger::seriealPrint_otherRegion_toggle(), adriToolsLogger::spiff_readCurrent(), adriToolsLogger::spiff_removeCurrent(), adriToolsLogger::spiff_toggle(), and adriToolsLogger::spiffAddLine_otherRegion_toggle().
adriToolLogger_serialMenu_region()
String adriToolLogger_serialMenu_region (String cmd, String value)
fonction pour le keyboard, active/desactive totalement la region voullu
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Parameters
[in] cmd The command
[in] value The value
Returns
""
Definition at line 476 of file logger.cpp.
{
     adriToolsLogger * _looger = adriToolsLogger_ptrGet();
     ADRI_LOGP(false, -1, -1, 0, "<<<", "");
     ADRI_LOGP(false, -1, 0, 2,"","");
     ADRI_LOGP(false, -1, 2, 2, "cmd: %s - value: %S", cmd.c_str(), value.c_str());
     int pos = value.toInt();
     _looger->activateByRegion_toggle(pos);
     ADRI_LOGP(false, -1, 1, 2,"","");
     ADRI_LOGP(false, -1, -1, 0, ">>>", "");
     return "";
 }
References adriToolsLogger::activateByRegion_toggle(), ADRI_LOGP, and adriToolsLogger_ptrGet().
adriToolLogger_serialMenu_regionAddLine()
String adriToolLogger_serialMenu_regionAddLine (String cmd, String value)
fonction pour le keyboard, active/desactive "littlefs" pour la region voullue
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Parameters
[in] cmd The command
[in] value The value
Returns
""
Definition at line 499 of file logger.cpp.
{
     adriToolsLogger * _looger = adriToolsLogger_ptrGet();
     ADRI_LOGP(false, -1, -1, 0, "<<<", "");
     ADRI_LOGP(false, -1, 0, 2,"","");
     ADRI_LOGP(false, -1, 2, 2, "cmd: %s - value: %S", cmd.c_str(), value.c_str());
     int pos = value.toInt();
     _looger->activateByRegion_toggleAddLine(pos);
     ADRI_LOGP(false, -1, 1, 2,"","");
     ADRI_LOGP(false, -1, -1, 0, ">>>", "");
     return "";
 }
References adriToolsLogger::activateByRegion_toggleAddLine(), ADRI_LOGP, and adriToolsLogger_ptrGet().
adriToolLogger_serialMenu_regionSerialPrint()
String adriToolLogger_serialMenu_regionSerialPrint (String cmd, String value)
fonction pour le keyboard, active/desactive "printf" pour la region voullue
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Parameters
[in] cmd The command
[in] value The value
Returns
""
Definition at line 522 of file logger.cpp.
{
     adriToolsLogger * _looger = adriToolsLogger_ptrGet();
     ADRI_LOGP(false, -1, -1, 0, "<<<", "");
     ADRI_LOGP(false, -1, 0, 2,"","");
     ADRI_LOGP(false, -1, 2, 2, "cmd: %s - value: %S", cmd.c_str(), value.c_str());
     int pos = value.toInt();
     _looger->activateByRegion_toggleSerial(pos);
     ADRI_LOGP(false, -1, 1, 2,"","");
     ADRI_LOGP(false, -1, -1, 0, ">>>", "");
     return "";
 }
References adriToolsLogger::activateByRegion_toggleSerial(), ADRI_LOGP, and adriToolsLogger_ptrGet().
adriToolsLogger_ptrGet()
adriToolsLogger* adriToolsLogger_ptrGet ()
ptr ver la dernierre instance de la classe "adriToolsLogger"
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Returns
ptr
Definition at line 212 of file logger.cpp.
{
     if (adriToolsLogger_ptr == nullptr) adriToolsLogger_ptr = new adriToolsLogger();
     return adriToolsLogger_ptr;
 }
References adriToolsLogger_ptr.
Referenced by adriToolLogger_serialMenu_cmd(), adriToolLogger_serialMenu_region(), adriToolLogger_serialMenu_regionAddLine(), adriToolLogger_serialMenu_regionSerialPrint(), esp_log_print_lines(), esp_log_printf_(), adriToolsLogger::printer_displayMod(), and adriToolsLogger::printer_serial().
esp_log_print_lines()
void esp_log_print_lines (boolean addLine, int region, int lvl, int mod, String pLine, String func, String var, const char * tag)
Definition at line 673 of file logger.cpp.
{
     adriToolsLogger * _looger = adriToolsLogger_ptrGet();
     String  pTag        = String(tag);
     int     searchCR    = 0;
     searchCR = _looger->strContains('\n', tag);
     String  varP        = var;
     String  title       = "";
     switch (lvl) {
         case 0:
             title = "[<<START>>]";
         break;
         case 1:
             title = "[<<END>>]";
         break;
         default:break;
     }
     if (pLine != "") {
         if (pTag != "")     {
             String cr = "";
             int len = strlen(tag);
             if (searchCR > 0)   {
                 if ((pTag.substring(len-1) == "\n") && (pTag.substring(0, 1) == "\n")  ) {
                     pTag.remove(len-1, 1);
                     pTag.remove(0, 1);
                     cr = "\n";
                 } else {
                     if (pTag.substring(0,1)     == "\n") {pTag.remove(0, 1);}
                     if (pTag.substring(len-1)   == "\n") {pTag.remove(len-1, 1);}
                     cr = "\n";
                 }
                 if (varP != "") {
                     fssprintf(adriLogger_buffer1, "[%-97s][%-20s]%s%s\t[%s]",
                             pLine.c_str(),
                             varP.c_str(),
                             title.c_str(),
                             cr.c_str(),
                             pTag.c_str()
                         );
                 } else {
                     fssprintf(adriLogger_buffer1, "[%-97s]%s%s\t[%s]",
                             pLine.c_str(),
                             title.c_str(),
                             cr.c_str(),
                             pTag.c_str()
                         );
                 }
             }  else {
                 if (varP != "") {
                     fssprintf(adriLogger_buffer1, "[%-97s][%-20s]%s[%s]",
                             pLine.c_str(),
                             varP.c_str(),
                             title.c_str(),
                             pTag.c_str()
                         );
                 } else {
                     fssprintf(adriLogger_buffer1, "[%-97s]%s[%s]",
                             pLine.c_str(),
                             title.c_str(),
                             pTag.c_str()
                         );
                 }
             }
         } else {
             if (varP != "") {fssprintf(adriLogger_buffer1, "[%-97s][%-20s]%s", pLine.c_str(), varP.c_str(), title.c_str()); }
             else {fssprintf(adriLogger_buffer1, "[%-97s]%s", pLine.c_str(), title.c_str()); }
         }
     }
     else {
         if (pTag != "")     {
             String cr = "";
             int len = strlen(tag);
             if (searchCR > 0)   {
                 if ((pTag.substring(len-1) == "\n") && (pTag.substring(0, 1) == "\n")  ) {
                     pTag.remove(len-1, 1);
                     pTag.remove(0, 1);
                     cr = "\n";
                 } else {
                     if (pTag.substring(0,1)     == "\n") {pTag.remove(0, 1);}
                     if (pTag.substring(len-1)   == "\n") {pTag.remove(len-1, 1);}
                     cr = "\n";
                 }
                 if (varP != "") {
                     fssprintf(adriLogger_buffer1, "[%-20s]%s%s\t[%s]",
                             varP.c_str(),
                             title.c_str(),
                             cr.c_str(),
                             pTag.c_str()
                         );
                 } else {
                     fssprintf(adriLogger_buffer1, "%s%s\t[%s]",
                             title.c_str(),
                             cr.c_str(),
                             pTag.c_str()
                         );
                 }
             }  else {
                 if (varP != "") {
                     fssprintf(adriLogger_buffer1, "[%-20s]%s[%s]",
                             varP.c_str(),
                             title.c_str(),
                             pTag.c_str()
                         );
                 } else {
                     fssprintf(adriLogger_buffer1, "%s[%s]",
                             title.c_str(),
                             pTag.c_str()
                         );
                 }
             }
         } else {
             if (varP != "") {fssprintf(adriLogger_buffer1, "[%-20s]%s", varP.c_str(), title.c_str()); }
             else {fssprintf(adriLogger_buffer1, "%s",  title.c_str()); }
         }
     }
     _looger->printer_serial(addLine, region, lvl, adriLogger_buffer1 );
 }
References adriLogger_buffer1, adriToolsLogger_ptrGet(), adriToolsLogger::printer_serial(), adriToolsLogger::strContains(), and ArduinoTrace::strlen().
Referenced by esp_log_printf_().
esp_log_printf_() [1/3]
void esp_log_printf_ (boolean addLine, int region, int lvl, int mod, String line, String func, const char * tag)
Definition at line 922 of file logger.cpp.
{
     if (!adriToolsLogger_ptrGet()->printer_displayMod(region, lvl)) return;
     String pLine = "";
     switch (mod) {
         case 1:
             pLine = line;
             break;
         case 2:
             pLine = line + " " + func;
             break;
         default:
             break;
     }
     esp_log_print_lines(addLine, region, lvl, mod, pLine, func, (char*)"", tag );
 }
References adriToolsLogger_ptrGet(), and esp_log_print_lines().
esp_log_printf_() [2/3]
void esp_log_printf_ (int region, int lvl, int mod, String line, String func, const char * tag)
Definition at line 907 of file logger.cpp.
{
     if (!adriToolsLogger_ptrGet()->printer_displayMod(region, lvl)) return;
     String pLine = "";
     switch (mod) {
         case 1:
             pLine = line;
             break;
         case 2:
             pLine = line + " " + func;
             break;
         default:
             break;
     }
     esp_log_print_lines(true, region, lvl, mod, pLine, func, (char*)"", tag );
 }
References adriToolsLogger_ptrGet(), and esp_log_print_lines().
esp_log_printf_() [3/3]
void esp_log_printf_ (int region, int lvl, int mod, String line, String func, String var, const char * tag)
Definition at line 892 of file logger.cpp.
{
     if (!adriToolsLogger_ptrGet()->printer_displayMod(region, lvl)) return;
     String pLine = "";
     switch (mod) {
         case 1:
             pLine = line;
             break;
         case 2:
             pLine = line + " " + func;
             break;
         default:
             break;
     }
     esp_log_print_lines(true, region, lvl, mod, pLine, func, var, tag );
 }
References adriToolsLogger_ptrGet(), and esp_log_print_lines().
Variable Documentation
adriLogger_buffer1
char adriLogger_buffer1[1024]
Definition at line 102 of file logger.cpp.
Referenced by esp_log_print_lines().
adriToolsLogger_ptr
adriToolsLogger* adriToolsLogger_ptr = nullptr
Definition at line 202 of file logger.cpp.
Referenced by adriToolsLogger::adriToolsLogger(), and adriToolsLogger_ptrGet().
LOG_LEVEL_COLORS
const char* LOG_LEVEL_COLORS[] static
Initial value:
= {
    "",
    ADRITOOLSLOGGER_BOLD(ADRITOOLSLOGGER_COLOR_RED),
    ADRITOOLSLOGGER_COLOR(ADRITOOLSLOGGER_COLOR_YELLOW),
    ADRITOOLSLOGGER_COLOR(ADRITOOLSLOGGER_COLOR_GREEN),
    ADRITOOLSLOGGER_COLOR(ADRITOOLSLOGGER_COLOR_MAGENTA),
    ADRITOOLSLOGGER_COLOR(ADRITOOLSLOGGER_COLOR_CYAN),
    ADRITOOLSLOGGER_COLOR(ADRITOOLSLOGGER_COLOR_GRAY),
    ADRITOOLSLOGGER_COLOR(ADRITOOLSLOGGER_COLOR_WHITE),
}
Definition at line 91 of file logger.cpp.
Referenced by adriToolsLogger::printer_serial().