adri_tools_v2: logger.h File Reference
logger.h File Reference
#include <arduino.h>
#include "core.h"
Classes
class adriToolsLogger_region
crée une region atribbuer a un ou plusieur "printf" ou "LITTLEFS"
class adriToolsLogger
fournit des fonctionnalités utiles pour déboguer les croquis via "printf" ou "LITTLEFS"
Functions
adriToolsLogger * adriToolsLogger_ptrGet ()
ptr ver la dernierre instance de la classe "adriToolsLogger"
String adriToolLogger_serialMenu_region (String cmd, String value)
fonction pour le keyboard, active/desactive totalement la region voullu
String adriToolLogger_serialMenu_regionAddLine (String cmd, String value)
fonction pour le keyboard, active/desactive "littlefs" pour la region voullue
String adriToolLogger_serialMenu_regionSerialPrint (String cmd, String value)
fonction pour le keyboard, active/desactive "printf" pour la region voullue
String adriToolLogger_serialMenu_cmd (String cmd, String value)
fonction pour le keyboard, commnds menu
Function Documentation
adriToolLogger_serialMenu_cmd()
String adriToolLogger_serialMenu_cmd (String cmd, String value)
fonction pour le keyboard, commnds menu
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Parameters
[in] cmd The command
[in] value The value
Returns
""
Definition at line 545 of file logger.cpp.
{
     adriToolsLogger * _looger = adriToolsLogger_ptrGet();
     ADRI_LOGP(false, -1, -1, 0, "<<<", "");
     ADRI_LOGP(false, -1, 0, 2,"","");
     ADRI_LOGP(false, -1, 2, 2, "cmd: %s - value: %S", cmd.c_str(), value.c_str());
     int pos = value.toInt();
     if (value == "a") {
         _looger->serial_menu();
     } else if (value == "z") {
         _looger->printer_display_toggle();
     } else if (value == "e") {
         _looger->printer_heap_toggle();
     } else if (value == "r") {
         _looger->printer_timestamp_toggle();
     } else if (value == "t") {
         _looger->spiff_toggle();
     } else if (value == "y") {
         _looger->spiff_readCurrent();
     } else if (value == "u") {
         _looger->spiff_removeCurrent();
     } else if (value == "i") {
         _looger->spiffAddLine_otherRegion_toggle();
     } else if (value == "o") {
         _looger->seriealPrint_otherRegion_toggle();
     } else if (value == "p") {
         _looger->activateByRegion_print();
     } else {
         _looger->printer_displayMod_set(pos);
     }
     ADRI_LOGP(false, -1, 1, 2,"","");
     ADRI_LOGP(false, -1, -1, 0, ">>>", "");
     return "";
 }
References adriToolsLogger::activateByRegion_print(), ADRI_LOGP, adriToolsLogger_ptrGet(), adriToolsLogger::printer_display_toggle(), adriToolsLogger::printer_displayMod_set(), adriToolsLogger::printer_heap_toggle(), adriToolsLogger::printer_timestamp_toggle(), adriToolsLogger::serial_menu(), adriToolsLogger::seriealPrint_otherRegion_toggle(), adriToolsLogger::spiff_readCurrent(), adriToolsLogger::spiff_removeCurrent(), adriToolsLogger::spiff_toggle(), and adriToolsLogger::spiffAddLine_otherRegion_toggle().
adriToolLogger_serialMenu_region()
String adriToolLogger_serialMenu_region (String cmd, String value)
fonction pour le keyboard, active/desactive totalement la region voullu
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Parameters
[in] cmd The command
[in] value The value
Returns
""
Definition at line 476 of file logger.cpp.
{
     adriToolsLogger * _looger = adriToolsLogger_ptrGet();
     ADRI_LOGP(false, -1, -1, 0, "<<<", "");
     ADRI_LOGP(false, -1, 0, 2,"","");
     ADRI_LOGP(false, -1, 2, 2, "cmd: %s - value: %S", cmd.c_str(), value.c_str());
     int pos = value.toInt();
     _looger->activateByRegion_toggle(pos);
     ADRI_LOGP(false, -1, 1, 2,"","");
     ADRI_LOGP(false, -1, -1, 0, ">>>", "");
     return "";
 }
References adriToolsLogger::activateByRegion_toggle(), ADRI_LOGP, and adriToolsLogger_ptrGet().
adriToolLogger_serialMenu_regionAddLine()
String adriToolLogger_serialMenu_regionAddLine (String cmd, String value)
fonction pour le keyboard, active/desactive "littlefs" pour la region voullue
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Parameters
[in] cmd The command
[in] value The value
Returns
""
Definition at line 499 of file logger.cpp.
{
     adriToolsLogger * _looger = adriToolsLogger_ptrGet();
     ADRI_LOGP(false, -1, -1, 0, "<<<", "");
     ADRI_LOGP(false, -1, 0, 2,"","");
     ADRI_LOGP(false, -1, 2, 2, "cmd: %s - value: %S", cmd.c_str(), value.c_str());
     int pos = value.toInt();
     _looger->activateByRegion_toggleAddLine(pos);
     ADRI_LOGP(false, -1, 1, 2,"","");
     ADRI_LOGP(false, -1, -1, 0, ">>>", "");
     return "";
 }
References adriToolsLogger::activateByRegion_toggleAddLine(), ADRI_LOGP, and adriToolsLogger_ptrGet().
adriToolLogger_serialMenu_regionSerialPrint()
String adriToolLogger_serialMenu_regionSerialPrint (String cmd, String value)
fonction pour le keyboard, active/desactive "printf" pour la region voullue
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Parameters
[in] cmd The command
[in] value The value
Returns
""
Definition at line 522 of file logger.cpp.
{
     adriToolsLogger * _looger = adriToolsLogger_ptrGet();
     ADRI_LOGP(false, -1, -1, 0, "<<<", "");
     ADRI_LOGP(false, -1, 0, 2,"","");
     ADRI_LOGP(false, -1, 2, 2, "cmd: %s - value: %S", cmd.c_str(), value.c_str());
     int pos = value.toInt();
     _looger->activateByRegion_toggleSerial(pos);
     ADRI_LOGP(false, -1, 1, 2,"","");
     ADRI_LOGP(false, -1, -1, 0, ">>>", "");
     return "";
 }
References adriToolsLogger::activateByRegion_toggleSerial(), ADRI_LOGP, and adriToolsLogger_ptrGet().
adriToolsLogger_ptrGet()
adriToolsLogger* adriToolsLogger_ptrGet ()
ptr ver la dernierre instance de la classe "adriToolsLogger"
Author
AdriLighting
See also
https://github.com/AdriLighting/adri_tools_v2
Date
06/02/2021 12:46:34
Returns
ptr
Definition at line 212 of file logger.cpp.
{
     if (adriToolsLogger_ptr == nullptr) adriToolsLogger_ptr = new adriToolsLogger();
     return adriToolsLogger_ptr;
 }
References adriToolsLogger_ptr.
Referenced by adriToolLogger_serialMenu_cmd(), adriToolLogger_serialMenu_region(), adriToolLogger_serialMenu_regionAddLine(), adriToolLogger_serialMenu_regionSerialPrint(), esp_log_print_lines(), esp_log_printf_(), adriToolsLogger::printer_displayMod(), and adriToolsLogger::printer_serial().